### ISSUE TITLE
`ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError` when using fixtures

### ISSUE THREAD

**Issue by cercxtrova** [igorkasyanchuk/active_storage_validations#363]
Hello, thanks for this great gem.

I just upgraded to version 2.0.2 and I'm encountering an issue that I unfortunately can't resolve.

As mentioned in the ActiveStorage documentation here (https://guides.rubyonrails.org/active_storage_overview.html#adding-attachments-to-fixtures), I'm using fixtures to attach files to my records. These fixtures are used to populate my database in development and, of course, in tests.

There are no issues in development. However, in tests, I randomly get an error `ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError`. The most frustrating part is that the error almost always happens in GitHub Actions. The error can occur in any test if I call the fixture where a file is supposed to be attached.

Unfortunately, I don’t have any more information to provide. I had no issues on version 1.4.0, and the errors disappear when I comment out the validation in my model. Locally, I’d say the issue occurs less than 10% of the time, whereas it happens almost systematically in the CI. Notably, the problem disappears if, instead of using fixtures for my attachments, I run `Rake.application["db:fixtures:load"].invoke` in my `seeds.rb` then use the `.attach` method to attach my file. However, since it worked before and fixtures are very convenient, I’d like to continue using them if possible.

Do you have any idea about this?
Thanks

---

This is my model:

```ruby
class Accommodation < ApplicationRecord
  COVER_CONTENT_TYPES = %i[png jpeg].freeze
  COVER_MAX_MEGABYTES = 10

  has_one_attached :cover do |attachable|
    attachable.variant :medium, resize_to_fill: [800, 400], preprocessed: true
  end

  validates :cover,
    processable_file: true,
    content_type:     COVER_CONTENT_TYPES,
    size:             { less_than_or_equal_to: COVER_MAX_MEGABYTES.megabytes }
end
```

and these are my fixtures:

```YAML
# test/fixtures/accommodations.yml

one:
  name: Ocean View Retreat
  welcome_message: Welcome to our beautiful beach house! We hope you enjoy your stay.
  theme_color: rose
  address: 123 Seaside Lane
  city: Malibu
  zip_code: 90265
  state: CA
  country: USA
  phone_number: +12025550123
  activated: false
  user: one
```

```YAML
# test/fixtures/active_storage/attachments.yml

first_accommodation_cover_attachment:
  name: cover
  record: one (Accommodation)
  blob: first_accommodation_cover_blob
```

```YAML
# test/fixtures/active_storage/blobs.yml

first_accommodation_cover_blob: <%= ActiveStorage::FixtureSet.blob filename: "accommodation_cover.jpeg", service_name: "test_fixtures" %>
```

---

If it helps, this is my config for `test_fixtures` in `config/storage.yml`:

```YAML
test_fixtures:
  service: Disk
  root: <%= Rails.root.join("tmp/storage_fixtures") %>
```
