### ISSUE TITLE
The translation message is invalid according to the instructions

### ISSUE THREAD

**Issue by wuminzhe** [igorkasyanchuk/active_storage_validations#71]
```
en:
  errors:
    messages:
      content_type_invalid: "has an invalid content type"
      ...
```
does not work.

but if I put messages under activerecord errors, it works.
